version: 2.1

executors:
  docker-publisher:
    working_directory: ~/build
    environment:
      IMAGE_NAME: harrior/patient-app
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-and-test:
    working_directory: ~/build
    docker:
      - image: ubuntu

      - image: postgres:13.0-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: medical 

    steps:
      - checkout
      - run: 
          name: Install Node.js, Leiningen, and npm
          command: | 
                    apt update -y
                    apt install -y leiningen curl
                    curl -fsSL https://deb.nodesource.com/setup_19.x | bash - 
                    apt install -y nodejs
                    npm install
      - run: lein deps
      - run: lein test
      - run: lein uberjar
      - persist_to_workspace:
          root: ~/build
          paths:
            - target
            - Docker
    
  build-docker:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: ~/build
      - setup_remote_docker
      - run:
          name: Build latest Docker image
          command: docker build -f ./Docker/Dockerfile.build-docker -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker images
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: ~/build
          paths:
            - ./image.tar

  publish-docker:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - build-docker:
          requires:
            - build-and-test
      - publish-docker:
          requires:
            - build-docker
