version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file:
      - .env

  patients:
    depends_on:
      - db
    restart: 'always'
    ports:
      - '8000:8000'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.build